version: '3'
services:
  open-catan:
    container_name: open-catan
    image: fabrik/open-catan:dev
    ports:
      - "8000:80/tcp"
    volumes:
      - ./data:/var/www/html
    restart: unless-stopped
